"""create products table

Revision ID: dca6fd322029
Revises: None
Create Date: 2024-09-11 19:57:33.186907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dca6fd322029"
down_revision = None
branch_labels = None
depends_on = None

# Initial product data
initial_products = [
    {"sku": "ipd", "name": "Super iPad", "price": 549.99},
    {"sku": "mbp", "name": "MacBook Pro", "price": 1399.99},
    {"sku": "atv", "name": "Apple TV", "price": 109.50},
    {"sku": "vga", "name": "VGA adapter", "price": 30.00},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("sku"),
    )

    # Insert initial product data
    op.bulk_insert(
        sa.table(
            "products", sa.column("sku", sa.String()), sa.column("name", sa.String()), sa.column("price", sa.Float())
        ),
        initial_products,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
